apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-service
  labels:
    app: webapp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-service
  template:
    metadata:
      labels:
        app: webapp-service
      name: webapp-service
    spec:
      containers:
        - name: webapp-service
          image: filhoeduardo83/webapp:1.0
          ports:
            - containerPort: 3000
          env:
            - name: APPLICATION_ENVIRONMENT
              value: prod
            - name: APPLICATION_PORT
              value: "3000"
            - name: REACT_APP_API_AUTH_URL
              value: http://auth-service:8000
            - name: REACT_APP_API_SINGLE_REGISTRY_URL
              value: http://single-registry-service:7000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-port
spec:
  type: NodePort
  selector:
    app: webapp-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003